### ISSUE TITLE
what server does this require 

### ISSUE THREAD

**Issue by powderedd** [General-Infinity/FlashTube#1]
i wanna host it so i can connec on all my windows PCs connected to my domain
also does it support MS server 2003?

**Comment by mvoolt** [comment]
sorry but were you meant to look up how to make an active directory on windows server?

if you meant connecting to a pc from a web browser, maybe give apache guacamole a try?

if not, look up how to run a php project (i can't be bothered to explain it all here)

**Comment by powderedd** [comment]
no i didnt, i meant so i could watch all my flash movies and MP4s on my windows PCS

**Comment by mvoolt** [comment]
the project isn't finished so look into peertube instead

**Comment by powderedd** [comment]
oh that doesnt support ie but i think i got PHP running on my server(?)

**Comment by mvoolt** [comment]
do you really need internet explorer in the year 2021?
if so just make a simple page to links to flvs/swfs and mp4s

**Comment by powderedd** [comment]
maybe
